exclude:
  - 'app/assets/stylesheets/scaffolds.scss'
  - 'vendor/bundle/*'

linters:
  BorderZero:
    enabled: false

  ColorVariable:
    enabled: false

  DeclarationOrder:
    enabled: false

  DuplicateProperty:
    enabled: false

  IdSelector:
    enabled: false

  Indentation:
    enabled: true
    width: 2

  ImportantRule:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: '^[a-zA-Z][-_a-zA-Z0-9]*$'
    class_convention: '^[a-zA-Z][-_a-zA-Z0-9]*$'

  SingleLinePerSelector:
    enabled: false
